// LogDoc Plugin SDK v2: gRPC subprocess plugins.
//
// A plugin is a standalone executable. The core launches it, reads one
// handshake line from its stdout:
//
//	LOGDOC-PLUGIN|1|tcp|127.0.0.1:PORT
//
// then connects over gRPC and drives one of the services below. Two kinds:
//
//   - source: receives data by its own means (listeners, polling, ...) and
//     streams parsed entries into the core (v1 "sink plugins");
//   - pipe: is called by the core when a notification rule fires
//     (v1 "pipe plugins").
//
// The plugin must exit when its stdin closes — that is how it learns the
// core is gone.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: plugin.proto

package pluginpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entry — one log entry (mirrors the core model).
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnixNano    int64                  `protobuf:"varint,1,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"` // 0 = let the core stamp arrival time
	App           string                 `protobuf:"bytes,2,opt,name=app,proto3" json:"app,omitempty"`
	Src           string                 `protobuf:"bytes,3,opt,name=src,proto3" json:"src,omitempty"`
	Pid           string                 `protobuf:"bytes,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Lvl           uint32                 `protobuf:"varint,5,opt,name=lvl,proto3" json:"lvl,omitempty"` // 0..6: DEBUG INFO LOG WARN ERROR SEVERE PANIC
	Msg           string                 `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`  // mandatory
	Fields        map[string]string      `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

func (x *Entry) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Entry) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *Entry) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *Entry) GetLvl() uint32 {
	if x != nil {
		return x.Lvl
	}
	return 0
}

func (x *Entry) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Entry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

// PluginConfig — the instance name and the flattened `config:` map of this
// plugin's entry in logdoc.yml.
type PluginConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginConfig) Reset() {
	*x = PluginConfig{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginConfig) ProtoMessage() {}

func (x *PluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginConfig.ProtoReflect.Descriptor instead.
func (*PluginConfig) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginConfig) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

// Info — what a plugin reports about itself during the handshake.
type Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"` // "source" | "pipe"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Info) Reset() {
	*x = Info{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Info) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Info) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// Event — a fired notification rule (pipe plugins).
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          string                 `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // error_threshold | silence
	App           string                 `protobuf:"bytes,3,opt,name=app,proto3" json:"app,omitempty"`
	Count         int32                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Window        string                 `protobuf:"bytes,5,opt,name=window,proto3" json:"window,omitempty"`
	TsUnixNano    int64                  `protobuf:"varint,6,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	Message       string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,8,rep,name=entries,proto3" json:"entries,omitempty"` // matched entries, capped by the core
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetApp() string {
	if x != nil {
		return x.App
	}
	return ""
}

func (x *Event) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Event) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *Event) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x10logdoc.plugin.v1\"\xfb\x01\n" +
	"\x05Entry\x12 \n" +
	"\fts_unix_nano\x18\x01 \x01(\x03R\n" +
	"tsUnixNano\x12\x10\n" +
	"\x03app\x18\x02 \x01(\tR\x03app\x12\x10\n" +
	"\x03src\x18\x03 \x01(\tR\x03src\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\tR\x03pid\x12\x10\n" +
	"\x03lvl\x18\x05 \x01(\rR\x03lvl\x12\x10\n" +
	"\x03msg\x18\x06 \x01(\tR\x03msg\x12;\n" +
	"\x06fields\x18\a \x03(\v2#.logdoc.plugin.v1.Entry.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x01\n" +
	"\fPluginConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12B\n" +
	"\x06config\x18\x02 \x03(\v2*.logdoc.plugin.v1.PluginConfig.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\x04Info\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"\xde\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04rule\x18\x01 \x01(\tR\x04rule\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x10\n" +
	"\x03app\x18\x03 \x01(\tR\x03app\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x05R\x05count\x12\x16\n" +
	"\x06window\x18\x05 \x01(\tR\x06window\x12 \n" +
	"\fts_unix_nano\x18\x06 \x01(\x03R\n" +
	"tsUnixNano\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x121\n" +
	"\aentries\x18\b \x03(\v2\x17.logdoc.plugin.v1.EntryR\aentries\"\a\n" +
	"\x05Empty2\x8d\x01\n" +
	"\fSourcePlugin\x12;\n" +
	"\bDescribe\x12\x17.logdoc.plugin.v1.Empty\x1a\x16.logdoc.plugin.v1.Info\x12@\n" +
	"\x03Run\x12\x1e.logdoc.plugin.v1.PluginConfig\x1a\x17.logdoc.plugin.v1.Entry0\x012\xc9\x01\n" +
	"\n" +
	"PipePlugin\x12;\n" +
	"\bDescribe\x12\x17.logdoc.plugin.v1.Empty\x1a\x16.logdoc.plugin.v1.Info\x12D\n" +
	"\tConfigure\x12\x1e.logdoc.plugin.v1.PluginConfig\x1a\x17.logdoc.plugin.v1.Empty\x128\n" +
	"\x04Fire\x12\x17.logdoc.plugin.v1.Event\x1a\x17.logdoc.plugin.v1.EmptyB/Z-github.com/LogDoc-org/logdoc/pkg/sdk/pluginpbb\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_plugin_proto_goTypes = []any{
	(*Entry)(nil),        // 0: logdoc.plugin.v1.Entry
	(*PluginConfig)(nil), // 1: logdoc.plugin.v1.PluginConfig
	(*Info)(nil),         // 2: logdoc.plugin.v1.Info
	(*Event)(nil),        // 3: logdoc.plugin.v1.Event
	(*Empty)(nil),        // 4: logdoc.plugin.v1.Empty
	nil,                  // 5: logdoc.plugin.v1.Entry.FieldsEntry
	nil,                  // 6: logdoc.plugin.v1.PluginConfig.ConfigEntry
}
var file_plugin_proto_depIdxs = []int32{
	5, // 0: logdoc.plugin.v1.Entry.fields:type_name -> logdoc.plugin.v1.Entry.FieldsEntry
	6, // 1: logdoc.plugin.v1.PluginConfig.config:type_name -> logdoc.plugin.v1.PluginConfig.ConfigEntry
	0, // 2: logdoc.plugin.v1.Event.entries:type_name -> logdoc.plugin.v1.Entry
	4, // 3: logdoc.plugin.v1.SourcePlugin.Describe:input_type -> logdoc.plugin.v1.Empty
	1, // 4: logdoc.plugin.v1.SourcePlugin.Run:input_type -> logdoc.plugin.v1.PluginConfig
	4, // 5: logdoc.plugin.v1.PipePlugin.Describe:input_type -> logdoc.plugin.v1.Empty
	1, // 6: logdoc.plugin.v1.PipePlugin.Configure:input_type -> logdoc.plugin.v1.PluginConfig
	3, // 7: logdoc.plugin.v1.PipePlugin.Fire:input_type -> logdoc.plugin.v1.Event
	2, // 8: logdoc.plugin.v1.SourcePlugin.Describe:output_type -> logdoc.plugin.v1.Info
	0, // 9: logdoc.plugin.v1.SourcePlugin.Run:output_type -> logdoc.plugin.v1.Entry
	2, // 10: logdoc.plugin.v1.PipePlugin.Describe:output_type -> logdoc.plugin.v1.Info
	4, // 11: logdoc.plugin.v1.PipePlugin.Configure:output_type -> logdoc.plugin.v1.Empty
	4, // 12: logdoc.plugin.v1.PipePlugin.Fire:output_type -> logdoc.plugin.v1.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
