// LogDoc Plugin SDK v2: gRPC subprocess plugins.
//
// A plugin is a standalone executable. The core launches it, reads one
// handshake line from its stdout:
//
//	LOGDOC-PLUGIN|1|tcp|127.0.0.1:PORT
//
// then connects over gRPC and drives one of the services below. Two kinds:
//
//   - source: receives data by its own means (listeners, polling, ...) and
//     streams parsed entries into the core (v1 "sink plugins");
//   - pipe: is called by the core when a notification rule fires
//     (v1 "pipe plugins").
//
// The plugin must exit when its stdin closes — that is how it learns the
// core is gone.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: plugin.proto

package pluginpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SourcePlugin_Describe_FullMethodName = "/logdoc.plugin.v1.SourcePlugin/Describe"
	SourcePlugin_Run_FullMethodName      = "/logdoc.plugin.v1.SourcePlugin/Run"
)

// SourcePluginClient is the client API for SourcePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SourcePlugin — data intake. Run blocks for the lifetime of the plugin,
// streaming entries; the core cancels the stream on shutdown and restarts
// the subprocess if it exits or the stream breaks.
type SourcePluginClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Info, error)
	Run(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entry], error)
}

type sourcePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewSourcePluginClient(cc grpc.ClientConnInterface) SourcePluginClient {
	return &sourcePluginClient{cc}
}

func (c *sourcePluginClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Info, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Info)
	err := c.cc.Invoke(ctx, SourcePlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sourcePluginClient) Run(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Entry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SourcePlugin_ServiceDesc.Streams[0], SourcePlugin_Run_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PluginConfig, Entry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourcePlugin_RunClient = grpc.ServerStreamingClient[Entry]

// SourcePluginServer is the server API for SourcePlugin service.
// All implementations must embed UnimplementedSourcePluginServer
// for forward compatibility.
//
// SourcePlugin — data intake. Run blocks for the lifetime of the plugin,
// streaming entries; the core cancels the stream on shutdown and restarts
// the subprocess if it exits or the stream breaks.
type SourcePluginServer interface {
	Describe(context.Context, *Empty) (*Info, error)
	Run(*PluginConfig, grpc.ServerStreamingServer[Entry]) error
	mustEmbedUnimplementedSourcePluginServer()
}

// UnimplementedSourcePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSourcePluginServer struct{}

func (UnimplementedSourcePluginServer) Describe(context.Context, *Empty) (*Info, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedSourcePluginServer) Run(*PluginConfig, grpc.ServerStreamingServer[Entry]) error {
	return status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedSourcePluginServer) mustEmbedUnimplementedSourcePluginServer() {}
func (UnimplementedSourcePluginServer) testEmbeddedByValue()                      {}

// UnsafeSourcePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SourcePluginServer will
// result in compilation errors.
type UnsafeSourcePluginServer interface {
	mustEmbedUnimplementedSourcePluginServer()
}

func RegisterSourcePluginServer(s grpc.ServiceRegistrar, srv SourcePluginServer) {
	// If the following call panics, it indicates UnimplementedSourcePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SourcePlugin_ServiceDesc, srv)
}

func _SourcePlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SourcePluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SourcePlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SourcePluginServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SourcePlugin_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PluginConfig)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SourcePluginServer).Run(m, &grpc.GenericServerStream[PluginConfig, Entry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SourcePlugin_RunServer = grpc.ServerStreamingServer[Entry]

// SourcePlugin_ServiceDesc is the grpc.ServiceDesc for SourcePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SourcePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logdoc.plugin.v1.SourcePlugin",
	HandlerType: (*SourcePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _SourcePlugin_Describe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _SourcePlugin_Run_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

const (
	PipePlugin_Describe_FullMethodName  = "/logdoc.plugin.v1.PipePlugin/Describe"
	PipePlugin_Configure_FullMethodName = "/logdoc.plugin.v1.PipePlugin/Configure"
	PipePlugin_Fire_FullMethodName      = "/logdoc.plugin.v1.PipePlugin/Fire"
)

// PipePluginClient is the client API for PipePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PipePlugin — notification delivery. Configure is called once after every
// (re)start, Fire once per fired rule.
type PipePluginClient interface {
	Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Info, error)
	Configure(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (*Empty, error)
	Fire(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error)
}

type pipePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewPipePluginClient(cc grpc.ClientConnInterface) PipePluginClient {
	return &pipePluginClient{cc}
}

func (c *pipePluginClient) Describe(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Info, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Info)
	err := c.cc.Invoke(ctx, PipePlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipePluginClient) Configure(ctx context.Context, in *PluginConfig, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PipePlugin_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipePluginClient) Fire(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PipePlugin_Fire_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PipePluginServer is the server API for PipePlugin service.
// All implementations must embed UnimplementedPipePluginServer
// for forward compatibility.
//
// PipePlugin — notification delivery. Configure is called once after every
// (re)start, Fire once per fired rule.
type PipePluginServer interface {
	Describe(context.Context, *Empty) (*Info, error)
	Configure(context.Context, *PluginConfig) (*Empty, error)
	Fire(context.Context, *Event) (*Empty, error)
	mustEmbedUnimplementedPipePluginServer()
}

// UnimplementedPipePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPipePluginServer struct{}

func (UnimplementedPipePluginServer) Describe(context.Context, *Empty) (*Info, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedPipePluginServer) Configure(context.Context, *PluginConfig) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedPipePluginServer) Fire(context.Context, *Event) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Fire not implemented")
}
func (UnimplementedPipePluginServer) mustEmbedUnimplementedPipePluginServer() {}
func (UnimplementedPipePluginServer) testEmbeddedByValue()                    {}

// UnsafePipePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PipePluginServer will
// result in compilation errors.
type UnsafePipePluginServer interface {
	mustEmbedUnimplementedPipePluginServer()
}

func RegisterPipePluginServer(s grpc.ServiceRegistrar, srv PipePluginServer) {
	// If the following call panics, it indicates UnimplementedPipePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PipePlugin_ServiceDesc, srv)
}

func _PipePlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipePluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipePlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipePluginServer).Describe(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipePlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipePluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipePlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipePluginServer).Configure(ctx, req.(*PluginConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipePlugin_Fire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipePluginServer).Fire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipePlugin_Fire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipePluginServer).Fire(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// PipePlugin_ServiceDesc is the grpc.ServiceDesc for PipePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PipePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logdoc.plugin.v1.PipePlugin",
	HandlerType: (*PipePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _PipePlugin_Describe_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _PipePlugin_Configure_Handler,
		},
		{
			MethodName: "Fire",
			Handler:    _PipePlugin_Fire_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
