package graph

import (
	"fmt"
	"strings"
)

// Mermaid renders the topology as a Mermaid flowchart — pasteable into any
// Markdown file, GitHub comment, or architecture doc.
func Mermaid(t Topology) string {
	var b strings.Builder
	b.WriteString("flowchart LR\n")
	ids := mermaidIDs(t)
	for _, n := range t.Nodes {
		fmt.Fprintf(&b, "    %s[\"%s\"]\n", ids[n.App], escapeMermaid(n.App))
	}
	for _, e := range t.Edges {
		src, sok := ids[e.Src]
		dst, dok := ids[e.Dst]
		if !sok || !dok {
			continue
		}
		if e.RPS > 0 {
			fmt.Fprintf(&b, "    %s -->|%s| %s\n", src, escapeMermaid(rateLabel(e)), dst)
		} else {
			fmt.Fprintf(&b, "    %s --> %s\n", src, dst)
		}
	}
	return b.String()
}

// Markdown renders the topology as a human-readable architecture summary:
// a Mermaid diagram followed by service and link tables.
func Markdown(t Topology) string {
	var b strings.Builder
	b.WriteString("# Architecture\n\n")
	b.WriteString("Generated by LogDoc from runtime logs.\n\n")
	b.WriteString("```mermaid\n")
	b.WriteString(Mermaid(t))
	b.WriteString("```\n")

	if len(t.Nodes) > 0 {
		b.WriteString("\n## Services\n\n")
		b.WriteString("| Service | Entries | Errors | Last seen |\n")
		b.WriteString("|---|---:|---:|---|\n")
		for _, n := range t.Nodes {
			fmt.Fprintf(&b, "| %s | %d | %d | %s |\n",
				escapeMarkdown(n.App), n.Count, n.Errors, n.LastSeen.UTC().Format("2006-01-02 15:04:05 UTC"))
		}
	}
	if len(t.Edges) > 0 {
		b.WriteString("\n## Links\n\n")
		b.WriteString("| From | To | Origin | Rate | Error rate |\n")
		b.WriteString("|---|---|---|---:|---:|\n")
		for _, e := range t.Edges {
			rate := "—"
			if e.RPS > 0 {
				rate = fmt.Sprintf("%.2f rps", e.RPS)
			}
			fmt.Fprintf(&b, "| %s | %s | %s | %s | %.2f%% |\n",
				escapeMarkdown(e.Src), escapeMarkdown(e.Dst), e.Origin, rate, e.ErrorRate*100)
		}
	}
	return b.String()
}

func rateLabel(e Edge) string {
	if e.ErrorRate > 0 {
		return fmt.Sprintf("%.1f rps, %.1f%% err", e.RPS, e.ErrorRate*100)
	}
	return fmt.Sprintf("%.1f rps", e.RPS)
}

// mermaidIDs maps app names to safe node identifiers (n0, n1, ...) so that
// arbitrary service names cannot break diagram syntax.
func mermaidIDs(t Topology) map[string]string {
	ids := make(map[string]string, len(t.Nodes))
	for i, n := range t.Nodes {
		ids[n.App] = fmt.Sprintf("n%d", i)
	}
	return ids
}

func escapeMermaid(s string) string {
	s = strings.ReplaceAll(s, `"`, "#quot;")
	s = strings.ReplaceAll(s, "|", "#124;")
	return s
}

func escapeMarkdown(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}
